version: "3.7"
services:
  app:
    container_name: backbone
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo

  mongodb_container:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
